package com.situ.mall.mapper;

import java.util.List;

import com.situ.mall.entity.Cart;

public interface CartMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cart
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cart
	 * @mbggenerated
	 */
	int insert(Cart record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cart
	 * @mbggenerated
	 */
	int insertSelective(Cart record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cart
	 * @mbggenerated
	 */
	Cart selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cart
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Cart record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cart
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Cart record);

	List<Cart> pageList(Cart cart);

	int deleteAll(String[] idArray);

	Cart selectByProductId(Integer productId);

	List<Cart> selectByUserId(Integer userId);

	int updateByProductId(Cart cart);

	int deleteByProductId(Integer productId);

	int updateChecked(Integer checked);
}