package com.situ.mall.mapper;

import org.apache.ibatis.annotations.Param;

import com.situ.mall.entity.User;

public interface UserMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user
	 *
	 * @mbggenerated
	 */
	int insert(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user
	 *
	 * @mbggenerated
	 */
	int insertSelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user
	 *
	 * @mbggenerated
	 */
	User selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(User record);

	/**
	 * 登录时检查用户名是否存在
	 * 
	 * @param username
	 * @return
	 */
	int checkUserName(String username);

	/**
	 * 登陆时检查用户名密码是否一致
	 * 
	 * @param username
	 * @param password
	 * @return
	 */
	User selectLogin(@Param("username") String username, @Param("password") String password);
}